# -*- coding: utf-8 -*-
"""blackjack do fabio.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zNW6YHCPnwtb6l1bZvpuKLIDrUjc-7Bv

Blackjack python
"""

import random

dindin = 100
dindinc = 100000
dindinrodada = 0

class carta(object):
    def __init__(self, numero, naipe):
        self.numero = numero
        self.naipe = naipe

    def valor(self):
        if self.numero in ['K', 'Q', 'J']:
            return 10
        elif self.numero == "A":
            return 11
        else:
            return int(self.numero)

    def __str__(self):
        return f'{self.numero} de {self.naipe}'

class baralho(object):
    def __init__(self):
        numeros = ['A', 2, 3, 4, 5, 6, 7, 8, 9, 10, "J", 'Q', "K"]
        naipes = ['Copas', "Ouros", 'Paus', 'Espadas']
        self.cartas = [carta(numero, naipe) for naipe in naipes for numero in numeros]
        random.shuffle(self.cartas)

    def retirarcarta(self):
        return self.cartas.pop()

class mao(object):
    def __init__(self):
        self.maoo = []

    def adicionarcarta(self, carta):
        self.maoo.append(carta)

    def calcularpontos(self):
        total = 0
        ases = 0
        for carta_atual in self.maoo:  # Nome ajustado para evitar conflitos
            if carta_atual.numero == 'A':
                ases += 1
            total += carta_atual.valor()
        while total > 21 and ases > 0:
            total -= 10
            ases -= 1
        return total

while dindin > 0:
    print(' ')
    print('--------------------------')
    print('Seu dinheiro:', dindin)
    bjogo = baralho()
    bmao = mao()
    crupie = mao()
    print(' ')

    crupie.adicionarcarta(bjogo.retirarcarta())
    crupie.adicionarcarta(bjogo.retirarcarta())
    totalc = crupie.calcularpontos()
    print(' ')
    print(f"Primeira carta do crupiê: {crupie.maoo[0]}")  # Exibe apenas a primeira carta.
    print("A segunda carta está virada para baixo.")
    print(' ')

    bmao.adicionarcarta(bjogo.retirarcarta())
    bmao.adicionarcarta(bjogo.retirarcarta())
    total = bmao.calcularpontos()
    print('Cartas na mão do jogador:')
    for carta_atual in bmao.maoo:  # Nome ajustado
        print(carta_atual)

    print(' ')
    y = int(input('Quanto você deseja apostar? '))
    while True:
        if dindin < y or dindinc < y:
            print('Não há dinheiro pra essa aposta!')
            y = int(input('Digite um valor menor pra apostar: '))
        else:
            dindin -= y
            dindinc -= y
            dindinrodada = 2 * y
            print('Rodada valendo', dindinrodada)
            break

    if total > 21:
        print('Você estourou!')
        dindinc += dindinrodada

    elif total == 21:
        print('Blackjack!')
        dindin += dindinrodada

    else:
        while True:
            print(' ')
            x = int(input('Quer mais uma carta? [SIM(1)/NÃO(2)] '))
            print(' ')
            if x == 1:
                bmao.adicionarcarta(bjogo.retirarcarta())
                total = bmao.calcularpontos()
                for carta_atual in bmao.maoo:  # Nome ajustado
                    print(carta_atual)
                if total > 21:
                    print(' ')
                    print('Você estourou!')
                    print(f'Sua pontuação: {total}')
                    print(' ')
                    dindinc += dindinrodada
                    break
                elif total == 21:
                    print(' ')
                    print('Blackjack!')
                    print(f'Sua pontuação: {total}')
                    print(' ')
                    dindin += dindinrodada
                    break

            else:
                while totalc < 17:
                    crupie.adicionarcarta(bjogo.retirarcarta())
                    print('Crupiê comprou uma carta!')
                    print(' ')
                    totalc = crupie.calcularpontos()

                print(f'Sua pontuação: {total}')
                print(' ')
                print('Cartas na mão do crupiê:')
                for carta_atual in crupie.maoo:  # Nome ajustado
                    print(carta_atual)
                print(' ')
                print('Vamos apostar!')
                print('Pontuação do crupiê:', totalc)
                print(' ')

                if totalc == 21:
                    print('Crupiê fez blackjack, você perdeu!')
                    print(' ')
                    dindinc += dindinrodada

                elif totalc < 21 and total < 21 and totalc > total:
                    print('Você perdeu, a pontuação do crupiê é maior!')
                    print(' ')
                    dindinc += dindinrodada

                elif totalc < 21 and total < 21 and totalc < total:
                    print('Você ganhou, sua pontuação é maior!')
                    print(' ')
                    dindin += dindinrodada

                elif totalc < 21 and total < 21 and totalc == total:
                    print('Empatou!')
                    print(' ')
                    dindin += (dindinrodada / 2)
                    dindinc += (dindinrodada / 2)

                else:
                    print('Crupiê estourou, você venceu!')
                    print(' ')
                    dindin += dindinrodada
                break

    if dindin <= 0:
        print('Você está quebrado, o jogo acabou!')
        break

    continuar = int(input('Deseja continuar jogando? [SIM(1)/NÃO(2)] '))
    print(' ')
    if continuar != 1:
        print('Obrigado por jogar!')
        break

"""### **RESPOSTA DO PROFESSOR**"""

