# -*- coding: utf-8 -*-
"""verificador cartão de credito.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hwh5w6or_WKIVGG3hKBeK4xMEhxH715s
"""

def numero():
  while True:
    x=input('Digite o número do seu cartão de crédito(16 dígitos):')
    if x.isdigit():
      global y
      y=list(map(int,x))
      return(y)
    else:
      print('Digite apenas números!!')

def ext():
  global y
  while len(y)!=16:
    print('Número inválido, são necessários 16 dígitos!')
    numero()

def verif(y):
  v=[]
  c=y[::-1]

  i=c[1]*2
  if i>9:
    i=sum(map(int,str(i)))
  v.append(i)

  i2=c[3]*2
  if i2>9:
    i2=sum(map(int,str(i2)))
  v.append(i2)

  i3=c[5]*2
  if i3>9:
    i3=sum(map(int,str(i3)))
  v.append(i3)

  i4=c[7]*2
  if i4>9:
    i4=sum(map(int,str(i4)))
  v.append(i4)

  i5=c[9]*2
  if i5>9:
    i5=sum(map(int,str(i5)))
  v.append(i5)

  i6=c[11]*2
  if i6>9:
    i6=sum(map(int,str(i6)))
  v.append(i6)

  i7=c[13]*2
  if i7>9:
    i7=sum(map(int,str(i7)))
  v.append(i7)

  i8=c[15]*2
  if i8>9:
    i8=sum(map(int,str(i8)))
  v.append(i8)

  soma=(c[14]+c[12]+c[10]+c[8]+c[6]+c[4]+c[2]+c[0])+(v[0]+v[1]+v[2]+v[3]+v[4]+v[5]+v[6]+v[7])

  if soma%10 == 0:
    print(' ')
    print('Analisando...')
    print('Esse número de cartão de crédito é válido!')
  else:
    print(' ')
    print('Analisando...')
    print('Esse número de cartão de crédito não é válido!')

numero()
ext()
verif(y)