# -*- coding: utf-8 -*-
"""velhabonito.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eKN31C6s2p5VEJ3z6eSbd5TcMtxq0x0B

tentando fazer o velha mais bonitinho
"""

l=['1','2','3','4','5','6','7','8','9',]
vez=1
x=2
jogadas=0

def tabuleiro():

  print('|', l[0],'|', l[1],'|', l[2],'|',)
  print('-------------')
  print('|', l[3],'|', l[4],'|', l[5],'|',)
  print('-------------')
  print('|', l[6],'|', l[7],'|', l[8],'|',)

def jogador():
  if vez==1:
    print('É a vez do jogador 1(x):')
    print(' ')
  else:
    print('É a vez do jogador 2(o):')
    print(' ')

def jogada():
  global vez
  global jogadas
  print(" ")
  a=input('Qual casa deseja jogar?')

  if a==l[0]:
    l[0]='x' if vez==1 else 'o'
    vez = 2 if vez == 1 else 1
    print(' ')
  elif a==l[1]:
    l[1]='x' if vez==1 else 'o'
    vez = 2 if vez == 1 else 1
    print(' ')
  elif a==l[2]:
    l[2]='x' if vez==1 else 'o'
    vez = 2 if vez == 1 else 1
    print(' ')
  elif a==l[3]:
    l[3]='x' if vez==1 else 'o'
    vez = 2 if vez == 1 else 1
    print(' ')
  elif a==l[4]:
    l[4]='x' if vez==1 else 'o'
    vez = 2 if vez == 1 else 1
    print(' ')
  elif a==l[5]:
    l[5]='x' if vez==1 else 'o'
    vez = 2 if vez == 1 else 1
    print(' ')
  elif a==l[6]:
    l[6]='x' if vez==1 else 'o'
    vez = 2 if vez == 1 else 1
    print(' ')
  elif a==l[7]:
    l[7]='x' if vez==1 else 'o'
    vez = 2 if vez == 1 else 1
    print(' ')
  elif a==l[8]:
    l[8]='x' if vez==1 else 'o'
    vez = 2 if vez == 1 else 1
    print(' ')
  else:
    vez=1 if vez==1 else 2
    print('Jogada inválida!!')
    print(' ')
  jogadas=(jogadas+1)
  vencedor()
  jogador()
  tabuleiro()


def vencedor():
  if vez == 1 and (l[0]==l[1] and l[1]==l[2]) or (l[3]==l[4] and l[4]==l[5]) or (l[6]==l[7] and l[7]==l[8]) or (l[0]==l[3] and l[3]==l[6]) or (l[1]==l[4] and l[4]==l[7]) or (l[2]==l[5] and l[5]==l[8]) or (l[0]==l[4] and l[4]==l[8]) or (l[2]==l[4] and l[4]==l[6]):
    print('Jogador 1 venceu!!')
    print(' ')
    tabuleiro()
    sys.exit()

  elif vez == 2 and (l[0]==l[1] and l[1]==l[2]) or (l[3]==l[4] and l[4]==l[5]) or (l[6]==l[7] and l[7]==l[8]) or (l[0]==l[3] and l[3]==l[6]) or (l[1]==l[4] and l[4]==l[7]) or (l[2]==l[5] and l[5]==l[8]) or (l[0]==l[4] and l[4]==l[8]) or (l[2]==l[4] and l[4]==l[6]):
    print('Jogador 2 venceu!!')
    print(' ')
    tabuleiro()
    sys.exit()
  elif jogadas==9:
    print('Deu velha!!')
    print(' ')
    tabuleiro()
    sys.exit()

  else:
    jogador()
    tabuleiro()
    jogada()


jogador()
tabuleiro()
jogada()
vencedor()

